/**
 * Catalogo de banderas: codigo de `flag-icons`, nombre en espanol, region y nivel.
 *
 * El nivel (1-5) es lo que gradua la dificultad: 1 son las que conoce cualquiera,
 * 4 los paises que casi nadie ubica y 5 los territorios (Aruba, Islas Feroe,
 * Cataluna...). Los territorios muy conocidos (Puerto Rico, Groenlandia, Hong Kong,
 * Escocia) estan en el 3, asi aparecen antes que los raros, como pidio el
 * programador: los territorios entran a medida que sube la dificultad.
 *
 * Quedan afuera a proposito las banderas que en `flag-icons` son la de otro pais
 * (Guadalupe, Reunion, Mayotte, San Martin, San Bartolome, Guayana Francesa y
 * Martinica usan la francesa; Bouvet y Svalbard la noruega; Heard la australiana;
 * las islas menores de EE.UU. la estadounidense): serian preguntas sin respuesta.
 */

export type Region =
  | "sudamerica"
  | "norteamerica"
  | "caribe"
  | "europa"
  | "africa"
  | "medio-oriente"
  | "asia"
  | "oceania";

export interface Country {
  code: string;
  name: string;
  region: Region;
  tier: 1 | 2 | 3 | 4 | 5;
}

type Row = [code: string, name: string, region: Region, tier: Country["tier"]];

const ROWS: Row[] = [
  // ---------- Nivel 1: las que conoce cualquiera ----------
  ["ar", "Argentina", "sudamerica", 1],
  ["br", "Brasil", "sudamerica", 1],
  ["uy", "Uruguay", "sudamerica", 1],
  ["cl", "Chile", "sudamerica", 1],
  ["co", "Colombia", "sudamerica", 1],
  ["pe", "Perú", "sudamerica", 1],
  ["mx", "México", "norteamerica", 1],
  ["us", "Estados Unidos", "norteamerica", 1],
  ["ca", "Canadá", "norteamerica", 1],
  ["es", "España", "europa", 1],
  ["fr", "Francia", "europa", 1],
  ["it", "Italia", "europa", 1],
  ["de", "Alemania", "europa", 1],
  ["gb", "Reino Unido", "europa", 1],
  ["pt", "Portugal", "europa", 1],
  ["ch", "Suiza", "europa", 1],
  ["jp", "Japón", "asia", 1],
  ["cn", "China", "asia", 1],
  ["kr", "Corea del Sur", "asia", 1],
  ["in", "India", "asia", 1],
  ["au", "Australia", "oceania", 1],
  ["za", "Sudáfrica", "africa", 1],
  ["il", "Israel", "medio-oriente", 1],
  ["tr", "Turquía", "medio-oriente", 1],
  ["ru", "Rusia", "europa", 1],
  ["gr", "Grecia", "europa", 1],
  ["se", "Suecia", "europa", 1],
  ["nl", "Países Bajos", "europa", 1],
  ["cu", "Cuba", "caribe", 1],
  ["jm", "Jamaica", "caribe", 1],

  // ---------- Nivel 2: conocidas ----------
  ["ve", "Venezuela", "sudamerica", 2],
  ["bo", "Bolivia", "sudamerica", 2],
  ["py", "Paraguay", "sudamerica", 2],
  ["ec", "Ecuador", "sudamerica", 2],
  ["cr", "Costa Rica", "norteamerica", 2],
  ["pa", "Panamá", "norteamerica", 2],
  ["do", "República Dominicana", "caribe", 2],
  ["be", "Bélgica", "europa", 2],
  ["ie", "Irlanda", "europa", 2],
  ["at", "Austria", "europa", 2],
  ["pl", "Polonia", "europa", 2],
  ["no", "Noruega", "europa", 2],
  ["dk", "Dinamarca", "europa", 2],
  ["fi", "Finlandia", "europa", 2],
  ["ua", "Ucrania", "europa", 2],
  ["hr", "Croacia", "europa", 2],
  ["cz", "Chequia", "europa", 2],
  ["hu", "Hungría", "europa", 2],
  ["is", "Islandia", "europa", 2],
  ["nz", "Nueva Zelanda", "oceania", 2],
  ["eg", "Egipto", "africa", 2],
  ["ma", "Marruecos", "africa", 2],
  ["ng", "Nigeria", "africa", 2],
  ["sa", "Arabia Saudita", "medio-oriente", 2],
  ["ir", "Irán", "medio-oriente", 2],
  ["vn", "Vietnam", "asia", 2],
  ["th", "Tailandia", "asia", 2],
  ["id", "Indonesia", "asia", 2],
  ["ph", "Filipinas", "asia", 2],
  ["pk", "Pakistán", "asia", 2],
  ["kp", "Corea del Norte", "asia", 2],
  ["sg", "Singapur", "asia", 2],

  // ---------- Nivel 3: medianas, mas los territorios famosos ----------
  ["gt", "Guatemala", "norteamerica", 3],
  ["hn", "Honduras", "norteamerica", 3],
  ["sv", "El Salvador", "norteamerica", 3],
  ["ni", "Nicaragua", "norteamerica", 3],
  ["ht", "Haití", "caribe", 3],
  ["ro", "Rumania", "europa", 3],
  ["bg", "Bulgaria", "europa", 3],
  ["rs", "Serbia", "europa", 3],
  ["sk", "Eslovaquia", "europa", 3],
  ["si", "Eslovenia", "europa", 3],
  ["ba", "Bosnia y Herzegovina", "europa", 3],
  ["al", "Albania", "europa", 3],
  ["lt", "Lituania", "europa", 3],
  ["lv", "Letonia", "europa", 3],
  ["ee", "Estonia", "europa", 3],
  ["by", "Bielorrusia", "europa", 3],
  ["md", "Moldavia", "europa", 3],
  ["lu", "Luxemburgo", "europa", 3],
  ["mc", "Mónaco", "europa", 3],
  ["ad", "Andorra", "europa", 3],
  ["mt", "Malta", "europa", 3],
  ["cy", "Chipre", "europa", 3],
  ["va", "Ciudad del Vaticano", "europa", 3],
  ["ge", "Georgia", "europa", 3],
  ["dz", "Argelia", "africa", 3],
  ["tn", "Túnez", "africa", 3],
  ["ke", "Kenia", "africa", 3],
  ["gh", "Ghana", "africa", 3],
  ["sn", "Senegal", "africa", 3],
  ["cm", "Camerún", "africa", 3],
  ["et", "Etiopía", "africa", 3],
  ["ci", "Costa de Marfil", "africa", 3],
  ["ae", "Emiratos Árabes Unidos", "medio-oriente", 3],
  ["qa", "Catar", "medio-oriente", 3],
  ["iq", "Irak", "medio-oriente", 3],
  ["sy", "Siria", "medio-oriente", 3],
  ["lb", "Líbano", "medio-oriente", 3],
  ["jo", "Jordania", "medio-oriente", 3],
  ["kw", "Kuwait", "medio-oriente", 3],
  ["af", "Afganistán", "asia", 3],
  ["my", "Malasia", "asia", 3],
  ["bd", "Bangladés", "asia", 3],
  ["np", "Nepal", "asia", 3],
  ["kz", "Kazajistán", "asia", 3],
  ["mn", "Mongolia", "asia", 3],
  ["tw", "Taiwán", "asia", 3],
  ["pr", "Puerto Rico", "caribe", 3],
  ["gl", "Groenlandia", "norteamerica", 3],
  ["hk", "Hong Kong", "asia", 3],
  ["gb-sct", "Escocia", "europa", 3],
  ["gb-eng", "Inglaterra", "europa", 3],
  ["gb-wls", "Gales", "europa", 3],
  ["ps", "Palestina", "medio-oriente", 3],

  // ---------- Nivel 4: los paises que casi nadie ubica ----------
  ["gy", "Guyana", "sudamerica", 4],
  ["sr", "Surinam", "sudamerica", 4],
  ["bz", "Belice", "norteamerica", 4],
  ["bs", "Bahamas", "caribe", 4],
  ["bb", "Barbados", "caribe", 4],
  ["tt", "Trinidad y Tobago", "caribe", 4],
  ["ag", "Antigua y Barbuda", "caribe", 4],
  ["dm", "Dominica", "caribe", 4],
  ["gd", "Granada", "caribe", 4],
  ["kn", "San Cristóbal y Nieves", "caribe", 4],
  ["lc", "Santa Lucía", "caribe", 4],
  ["vc", "San Vicente y las Granadinas", "caribe", 4],
  ["mk", "Macedonia del Norte", "europa", 4],
  ["me", "Montenegro", "europa", 4],
  ["li", "Liechtenstein", "europa", 4],
  ["sm", "San Marino", "europa", 4],
  ["xk", "Kosovo", "europa", 4],
  ["am", "Armenia", "asia", 4],
  ["az", "Azerbaiyán", "asia", 4],
  ["kg", "Kirguistán", "asia", 4],
  ["tj", "Tayikistán", "asia", 4],
  ["tm", "Turkmenistán", "asia", 4],
  ["uz", "Uzbekistán", "asia", 4],
  ["lk", "Sri Lanka", "asia", 4],
  ["mm", "Birmania", "asia", 4],
  ["kh", "Camboya", "asia", 4],
  ["la", "Laos", "asia", 4],
  ["bt", "Bután", "asia", 4],
  ["mv", "Maldivas", "asia", 4],
  ["bn", "Brunéi", "asia", 4],
  ["tl", "Timor Oriental", "asia", 4],
  ["om", "Omán", "medio-oriente", 4],
  ["ye", "Yemen", "medio-oriente", 4],
  ["bh", "Baréin", "medio-oriente", 4],
  ["ly", "Libia", "africa", 4],
  ["sd", "Sudán", "africa", 4],
  ["ss", "Sudán del Sur", "africa", 4],
  ["ml", "Malí", "africa", 4],
  ["bf", "Burkina Faso", "africa", 4],
  ["ne", "Níger", "africa", 4],
  ["td", "Chad", "africa", 4],
  ["mr", "Mauritania", "africa", 4],
  ["gn", "Guinea", "africa", 4],
  ["gw", "Guinea-Bisáu", "africa", 4],
  ["gm", "Gambia", "africa", 4],
  ["sl", "Sierra Leona", "africa", 4],
  ["lr", "Liberia", "africa", 4],
  ["tg", "Togo", "africa", 4],
  ["bj", "Benín", "africa", 4],
  ["cv", "Cabo Verde", "africa", 4],
  ["cd", "República Democrática del Congo", "africa", 4],
  ["cg", "República del Congo", "africa", 4],
  ["ga", "Gabón", "africa", 4],
  ["gq", "Guinea Ecuatorial", "africa", 4],
  ["cf", "República Centroafricana", "africa", 4],
  ["st", "Santo Tomé y Príncipe", "africa", 4],
  ["ao", "Angola", "africa", 4],
  ["zm", "Zambia", "africa", 4],
  ["zw", "Zimbabue", "africa", 4],
  ["mz", "Mozambique", "africa", 4],
  ["mw", "Malaui", "africa", 4],
  ["tz", "Tanzania", "africa", 4],
  ["ug", "Uganda", "africa", 4],
  ["rw", "Ruanda", "africa", 4],
  ["bi", "Burundi", "africa", 4],
  ["er", "Eritrea", "africa", 4],
  ["dj", "Yibuti", "africa", 4],
  ["so", "Somalia", "africa", 4],
  ["mg", "Madagascar", "africa", 4],
  ["km", "Comoras", "africa", 4],
  ["sc", "Seychelles", "africa", 4],
  ["mu", "Mauricio", "africa", 4],
  ["bw", "Botsuana", "africa", 4],
  ["na", "Namibia", "africa", 4],
  ["ls", "Lesoto", "africa", 4],
  ["sz", "Esuatini", "africa", 4],
  ["pg", "Papúa Nueva Guinea", "oceania", 4],
  ["fj", "Fiyi", "oceania", 4],
  ["sb", "Islas Salomón", "oceania", 4],
  ["vu", "Vanuatu", "oceania", 4],
  ["ws", "Samoa", "oceania", 4],
  ["to", "Tonga", "oceania", 4],
  ["ki", "Kiribati", "oceania", 4],
  ["tv", "Tuvalu", "oceania", 4],
  ["nr", "Nauru", "oceania", 4],
  ["pw", "Palaos", "oceania", 4],
  ["mh", "Islas Marshall", "oceania", 4],
  ["fm", "Micronesia", "oceania", 4],

  // ---------- Nivel 5: territorios ----------
  ["aw", "Aruba", "caribe", 5],
  ["cw", "Curazao", "caribe", 5],
  ["sx", "Sint Maarten", "caribe", 5],
  ["bm", "Bermudas", "caribe", 5],
  ["ky", "Islas Caimán", "caribe", 5],
  ["vg", "Islas Vírgenes Británicas", "caribe", 5],
  ["vi", "Islas Vírgenes de EE. UU.", "caribe", 5],
  ["ai", "Anguila", "caribe", 5],
  ["ms", "Montserrat", "caribe", 5],
  ["tc", "Islas Turcas y Caicos", "caribe", 5],
  ["fo", "Islas Feroe", "europa", 5],
  ["ax", "Åland", "europa", 5],
  ["gi", "Gibraltar", "europa", 5],
  ["im", "Isla de Man", "europa", 5],
  ["je", "Jersey", "europa", 5],
  ["gg", "Guernsey", "europa", 5],
  ["gb-nir", "Irlanda del Norte", "europa", 5],
  ["es-ct", "Cataluña", "europa", 5],
  ["es-pv", "País Vasco", "europa", 5],
  ["es-ga", "Galicia", "europa", 5],
  ["eh", "Sahara Occidental", "africa", 5],
  ["mo", "Macao", "asia", 5],
  ["nc", "Nueva Caledonia", "oceania", 5],
  ["pf", "Polinesia Francesa", "oceania", 5],
  ["as", "Samoa Americana", "oceania", 5],
  ["gu", "Guam", "oceania", 5],
  ["ck", "Islas Cook", "oceania", 5],
  ["nu", "Niue", "oceania", 5],
];

export const COUNTRIES: readonly Country[] = ROWS.map(([code, name, region, tier]) => ({
  code,
  name,
  region,
  tier,
}));

export const BY_CODE: ReadonlyMap<string, Country> = new Map(COUNTRIES.map((c) => [c.code, c]));

/**
 * Familias de banderas que se confunden entre si. De aca salen las opciones
 * trampa en los niveles altos: con Chad en pantalla, Rumania, Andorra y Moldavia
 * son la pregunta de verdad.
 */
const LOOKALIKES: string[][] = [
  ["td", "ro", "ad", "md"],
  ["id", "mc", "pl", "sg"],
  ["ie", "ci", "it", "mx"],
  ["hu", "bg", "ir", "tj", "it"],
  ["nl", "lu", "ru", "fr", "hr", "sk", "si", "rs", "py"],
  ["no", "is", "dk", "se", "fi", "fo", "ax"],
  ["au", "nz", "fj", "tv", "ck", "gb"],
  ["ve", "co", "ec"],
  ["ar", "uy", "sv", "ni", "hn", "gt"],
  ["ml", "gn", "sn", "cm", "gh", "bf"],
  ["ye", "eg", "sy", "iq", "sd"],
  ["ae", "kw", "jo", "ps", "sd", "eh"],
  ["at", "lv", "lb", "pe"],
  ["be", "de", "ug"],
  ["qa", "bh"],
  ["bo", "gh", "lt", "et", "gw"],
  ["pk", "dz", "tr", "tn", "az", "mv", "ly"],
  ["us", "lr", "my", "pr", "cu", "cl", "tg"],
  ["bd", "jp", "pw", "la"],
  ["ke", "ss", "mw"],
  ["ga", "sl", "bw"],
  ["cn", "vn", "hk", "mo", "tw"],
  ["ua", "kz", "se"],
  ["gb", "gb-eng", "gb-sct", "gb-wls", "gb-nir"],
  ["vg", "ky", "tc", "ms", "ai", "bm"],
  ["es", "es-ct", "ad", "co"],
  ["ch", "dk", "ge", "to"],
  ["cr", "th", "kp"],
  ["do", "pa"],
  ["al", "me", "mk"],
  ["cd", "cg", "tz", "sc"],
  ["mr", "pk", "km"],
  ["cw", "aw", "nr", "fm"],
  ["sb", "bs", "vi"],
  ["lc", "ag", "kn", "dm"],
  ["gr", "uy", "pr"],
  ["mn", "kg", "bt", "np"],
  ["pf", "nc", "as", "gu", "nu"],
];

/** Codigos que se parecen a `code` (sin repetir y sin el propio). */
export function lookalikesOf(code: string): string[] {
  const out = new Set<string>();
  for (const group of LOOKALIKES) {
    if (!group.includes(code)) continue;
    for (const c of group) if (c !== code && BY_CODE.has(c)) out.add(c);
  }
  return [...out];
}
